version: '3'

services:
  app:
    build: .
    ports:
      - 4002:5000   # Ensure your backend is running on the correct internal port (5000 in this case)
    environment:
      - MONGO_URL=${DEV_DATABASE_URL}
      - NODE_ENV=development
      - PORT=5000  # Explicitly passing port 5000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - universal-books  # Attach to the shared network

networks:
  universal-books:
    external: true  # Use the external network
